// Generated by CoffeeScript 1.6.3
(function() {
  var showMessages;

  showMessages = (function() {
    var catchDom, closeMessages, dom, initialize, showMessage, st, suscribeEvents;
    st = {
      'button': 'button',
      'body': 'body',
      'showMessages': '.showMessages'
    };
    dom = {};
    catchDom = function() {
      dom.button = $(st.button);
      dom.body = $(st.body);
    };
    suscribeEvents = function() {
      dom.button.on('click', showMessage);
    };
    showMessage = function(evet) {
      var $contentHtml;
      $contentHtml = $('<div class="showMessages"><p>Que tengas un buen dia</p><a href="javascript:;">X</a></div>');
      dom.body.append($contentHtml).addClass('overflow');
      $(st.showMessages).animate({
        'marginBottom': '-10px'
      }, function() {
        return $(st.showMessages).animate({
          'marginBottom': '-20px'
        });
      });
      closeMessages();
    };
    closeMessages = function() {
      return $('.showMessages a').on('click', function() {
        $(st.showMessages).animate({
          'marginBottom': '0px'
        }, function() {
          return $(st.showMessages).animate({
            'marginBottom': '-80px'
          }, function() {
            $(st.showMessages).remove();
          });
        });
        return dom.body.removeClass('overflow');
      });
    };
    initialize = function() {
      catchDom();
      suscribeEvents();
    };
    return {
      init: initialize
    };
  })();

  $(document).on('ready', function() {
    showMessages.init();
  });

}).call(this);
